{
 "title": "Polkadot and parachains full monitoring",
 "description": "All in one monitoring for Substrate based Relay chain, Parachains and backups",
 "tags": [
  "polkadot",
  "kusama",
  "substrate",
  "relay chain",
  "parachain",
  "blockchain",
  "bld"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "node",
    "query": {
     "query": "label_values({job=\"mainnet\"},chain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Monitoring Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"localhost:9100\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"localhost:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"localhost:9100\"}) /  count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"localhost:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"localhost:9100\"})"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "description": "Used FS",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"/dev/md2\",instance=\"localhost:9100\"} * 100) / node_filesystem_size_bytes{device=\"/dev/md2\",instance=\"localhost:9100\"})",
     "legendFormat": "Disk 1"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"/dev/nvme1n1\",instance=\"localhost:9100\"} * 100) / node_filesystem_size_bytes{device=\"/dev/nvme1n1\",instance=\"localhost:9100\"})",
     "legendFormat": "Disk 2"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device=\"/dev/sda1\",instance=\"localhost:9100\"} * 100) / node_filesystem_size_bytes{device=\"/dev/sda1\",instance=\"localhost:9100\"})",
     "legendFormat": "Disk 3"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"localhost:9100\"} - node_memory_SwapFree_bytes{instance=\"localhost:9100\"}) / (node_memory_SwapTotal_bytes{instance=\"localhost:9100\"} )) * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"localhost:9100\"} - node_boot_time_seconds{instance=\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 1, "x": 23, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"localhost:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=\"localhost:9100\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=\"localhost:9100\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=\"localhost:9100\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"localhost:9100\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"localhost:9100\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"localhost:9100\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\"} - (node_memory_Cached_bytes{instance=\"localhost:9100\"} + node_memory_Buffers_bytes{instance=\"localhost:9100\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\"} + node_memory_Buffers_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"localhost:9100\"} - node_memory_SwapFree_bytes{instance=\"localhost:9100\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"localhost:9100\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"localhost:9100\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "I/O Usage Times",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "s", "label": "time" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"localhost:9100\"} [5m])",
     "legendFormat": "{{device}} - Time spent doing I/Os"
    }
   ]
  },
  { "title": "Backups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Chain",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"backup\"}"
    },
    {
     "expr": "substrate_block_height{job=\"backup\",status=\"best\"}"
    },
    {
     "expr": "substrate_block_height{job=\"backup\",status=\"finalized\"}"
    },
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"backup\"}"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"backup\",status=\"best\"}[7d])*60)"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"backup\",status=\"best\"}[1d])*60)"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"backup\",status=\"best\"}[1h])*60)"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"backup\",status=\"best\"}[5m])*60)"
    },
    {
     "expr": "up{job=\"backup\",instance=~\".*9615\"}"
    }
   ]
  },
  {
   "title": "libp2p peers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"backup\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "increase(substrate_block_height{status=\"best\",job=\"backup\"}[5m])/5",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (chain) (irate(node_cpu_seconds_total{mode=\"idle\",job='backup'}[1m])) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (chain) (irate(node_cpu_seconds_total{mode=\"idle\",job=\"backup\"}[1m])) * 100)"
    },
    {
     "expr": "avg by (chain)(node_load15{job=\"backup\"}) / count by (chain)(count by (chain,cpu)(node_cpu_seconds_total{job=\"backup\"})) * 100"
    },
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"backup\"} * 100) / node_memory_MemTotal_bytes{job=\"backup\"})"
    },
    {
     "expr": "100 - (sum by (chain) ((node_filesystem_avail_bytes{job=\"backup\",mountpoint=\"/\"})*100)) / (sum by (chain) (node_filesystem_size_bytes{job=\"backup\",mountpoint=\"/\"}))"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"backup\"}) by (chain)/8"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"backup\"}) by (chain)"
    },
    {
     "expr": "up{job=\"backup\",instance=~\".*9100\"}"
    },
    {
     "expr": "max by (chain) (irate(node_disk_io_time_seconds_total{job=\"backup\"} [1m]))"
    },
    {
     "expr": "node_time_seconds{job=\"backup\"} - node_boot_time_seconds{job=\"backup\"}"
    }
   ]
  },
  {
   "title": "Mainnet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hardware",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (chain) (irate(node_cpu_seconds_total{mode=\"idle\",job=\"mainnet\",chain=~'$node'}[1m])) * 100)"
      },
      {
       "expr": "avg by (chain)(node_load15{job=\"mainnet\",chain=~'$node'}) / count by (chain)(count by (chain,cpu)(node_cpu_seconds_total{job=\"mainnet\",chain=~'$node'})) * 100"
      },
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"mainnet\",chain=~'$node'} * 100) / node_memory_MemTotal_bytes{job=\"mainnet\",chain=~'$node'})"
      },
      {
       "expr": "100 - (sum by (chain) ((node_filesystem_avail_bytes{job=\"mainnet\",chain=~'$node',mountpoint=\"/\"})*100)) / (sum by (chain) (node_filesystem_size_bytes{job=\"mainnet\",chain=~'$node',mountpoint=\"/\"}))"
      },
      {
       "expr": "count(node_cpu_seconds_total{job=\"mainnet\",chain=~'$node'}) by (chain)/8"
      },
      {
       "expr": "sum(node_memory_MemTotal_bytes{job=\"mainnet\",chain=~'$node'}) by (chain)"
      },
      {
       "expr": "up{job=\"mainnet\",chain=~'$node',instance=~\".*9100\"}"
      },
      {
       "expr": "max by (chain) (irate(node_disk_io_time_seconds_total{job=\"mainnet\",chain=~'$node'} [1m]))"
      },
      {
       "expr": "node_time_seconds{job=\"mainnet\",chain=~'$node'} - node_boot_time_seconds{job=\"mainnet\",chain=~'$node'}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 10, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - (avg by (chain) (irate(node_cpu_seconds_total{mode=\"idle\",job='mainnet',chain=~'$node'}[1m])) * 100)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{job='mainnet',chain=~'$node'}[5m])*8",
       "legendFormat": "{{chain}} in {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{job='mainnet',chain=~'$node'}[5m])*8",
       "legendFormat": "{{chain}} out {{device}} "
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 10, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"mainnet\",chain=~'$node'} * 100) / node_memory_MemTotal_bytes{job=\"mainnet\",chain=~'$node'})",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "Chain",
     "type": "table",
     "gridPos": { "h": 10, "w": 10, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "substrate_build_info{job=\"mainnet\",chain=~'$node'}"
      },
      {
       "expr": "substrate_block_height{job=\"mainnet\",chain=~'$node',status=\"best\"}"
      },
      {
       "expr": "substrate_block_height{job=\"mainnet\",chain=~'$node',status=\"finalized\"}"
      },
      {
       "expr": "substrate_sub_libp2p_peers_count{job=\"mainnet\",chain=~'$node'}"
      },
      {
       "expr": "avg by (chain)(rate(substrate_block_height{job=\"mainnet\",chain=~'$node',status=\"best\"}[7d])*60)"
      },
      {
       "expr": "avg by (chain)(rate(substrate_block_height{job=\"mainnet\",chain=~'$node',status=\"best\"}[1d])*60)"
      },
      {
       "expr": "avg by (chain)(rate(substrate_block_height{job=\"mainnet\",chain=~'$node',status=\"best\"}[1h])*60)"
      },
      {
       "expr": "avg by (chain)(rate(substrate_block_height{job=\"mainnet\",chain=~'$node',status=\"best\"}[5m])*60)"
      },
      {
       "expr": "up{job=\"mainnet\",chain=~'$node',instance=~\".*9615\"}"
      }
     ]
    },
    {
     "title": "Active validator",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 10, "y": 20 },
     "targets": [
      {
       "expr": "polkadot_node_is_active_validator{job=\"mainnet\"}",
       "legendFormat": "{{chain}} validator"
      },
      {
       "expr": "polkadot_node_is_parachain_validator{job=\"mainnet\"}",
       "legendFormat": "{{chain}} para validator"
      }
     ]
    },
    {
     "title": "Block rate",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 20 },
     "targets": [
      {
       "expr": "increase(substrate_block_height{status=\"best\",job=\"mainnet\",chain=~'$node'}[5m])/5",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "libp2p peers",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 10, "y": 25 },
     "targets": [
      {
       "expr": "substrate_sub_libp2p_peers_count{job=\"mainnet\",chain=~'$node'}",
       "legendFormat": "{{chain}}"
      }
     ]
    },
    {
     "title": "Transaction queue",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "substrate_ready_transactions_number{job=\"mainnet\",chain=~'$node'}",
       "legendFormat": "{{chain}}"
      }
     ]
    }
   ]
  }
 ]
}