global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "mainnet"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.16.0.10:9615","172.16.0.10:9100"]
        labels:
          chain: 'Polkadot'
      - targets: ["172.16.0.11:9615","192.168.0.11:9100"]
        labels:
          chain: 'Kusama'
      - targets: ["172.16.1.10:9615","172.16.1.10:9100"]
        labels:
          chain: 'Astar'

  - job_name: "backup"
    scrape_interval: 5s
    static_configs:
      - targets: ["172.16.2.10:19615","172.16.2.10:9100"]
        labels:
          chain: 'Polkadot-backup'
      - targets: ["172.16.2.11:19615","172.16.2.11:9100"]
        labels:
          chain: 'Kusama-backup'
      - targets: ["172.16.3.10:9615","172.16.3.10:9100"]
        labels:
          chain: 'Astar-backup'